# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: El blog de la mujer Actual
email: todomujer@miadeo.com
description: > # this means to ignore newlines until "baseurl:"
  Que significa omg 
En la red se han estado creando por mucho tiempo un estilo de expresarse, son como un idioma paralelo a la realidad en donde podemos encontrar la expresión “omg” bastante compartida en redes sociales para referirse generalmente para algo muy especial que ha sucedido.

Hoy en el mundo de las redes sociales donde todos opinan y tienen la última palabra, leer la expresión “omg” no es para nada raro, al contrario es algo muy común y normal entre personas adultas y jóvenes, ya que se refiere a las siglas en ingles de la expresión “Oh My God” refiriéndose a una exclamación a nuestro señor Dios. Este tipo de exclamaciones los podemos ver en diferentes redes sociales sobre todo en Facebook o Twitter en donde más personas comparten ideas e imágenes que sorprenden a los usuarios poniendo así la famosa expresión “omg”.

Si tu eres de esas personas que les encanta estar en las redes sociales informándote y además debatiendo con muchas otras personas de diferentes tipos de dilemas te vas a encontrar definitivamente con esta expresión, e incluso tú te veras tentado a usarla porque nos resulta súper practico el tener que hacer este tipo de abreviaturas que significa un expresión muy larga de expresar para algunos. 

Con esta expresión en boca de todos o mejor dicho en los dedos de todos al escribirlo nos podemos dar cuenta como la sociedad cambia de generación en generación incluso en su forma de expresarse ya en redes sociales que sigue siendo aun de moda en todo el mundo. 

“Omg” es sin duda una de las palabras de moda hoy en día conjuntamente con otras jergas urbanas y cibernéticas que nacen de las conversaciones cotidianas que tienen millones de personas en todo el mundo y en diferentes idiomas porque así es el nivel de poder que tienen las redes sociales con la globalización. 

Para terminar el articulo solo queda decirte que sigas expresándote libremente en la internet que mientras todo sea de forma legal y respetuoso sin hacer daño a nadie podremos convivir en paz. 

http://ebest.cl

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
